# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Site settings
locale: "en-US"
title: "Dr. Oliver Sieber"
#title-seperator: "-"
#email: your-email@example.com
description: Vulnerability Researcher, Mathematician
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://c1bero.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "c1bero/c1bero.github.io"
twitter_username: c1bero
github_username:  c1bero
word_per_minute: 200

# Build settings
#theme: minima
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.26.1"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin: "dark" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Author settings
author:
  # name: "Dr. Oliver Sieber"
  avatar: "assets/images/active_lc_icon.png"
  bio: "Vulnerability Researcher"
  location: "Germany"
  github: "c1bero/"
  linkedin: "oliver-sieber-8a9823203"
  twitter: "c1bero"

enable_copy_code_button: true

atom_feed:
  hide: true

# Read settings
include:
  - .htaccess
  - _pages


# Output
permalink: /:categories/:title/

# Markdown settings
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    block:
      line_numbers: false

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: false
